services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FINE_TUNING_MODEL
        value: ft:gpt-4o-mini-2024-07-18:curso-llm::C3nyJrmy
